# Generated by Django 5.2.5 on 2025-09-14 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0004_useranswer_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='useranswer',
            name='quiz_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
