# Generated by Django 5.2.5 on 2025-09-15 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0007_remove_useranswer_result'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difficulty', models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], max_length=20)),
                ('pdf', models.FileField(upload_to='quiz_pdfs/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('subtopic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='space.subtopic')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='space.topic')),
            ],
        ),
        migrations.AddField(
            model_name='mcqquestion',
            name='quiz_upload',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='mcqs', to='space.quizupload'),
        ),
    ]
