# Generated by Django 5.2.5 on 2025-09-15 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0008_quizupload_mcqquestion_quiz_upload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mcqquestion',
            name='quiz_upload',
        ),
        migrations.DeleteModel(
            name='QuizUpload',
        ),
    ]
